spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/spring_boot_test?characterEncoding=utf-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
      cache: false
      encoding: UTF-8
      mode: HTML5

mybatis:
  configuration:
    use-generated-keys: true
    use-column-label: true
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    cache-enabled: true
  type-aliases-package: com.ecjtu.kongtao.bean
  mapper-locations: classpath:mapper/*.xml